import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Rana',
      email: 'rana@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Sourav',
      email: 'sourav@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Deshal Bull',
      slug: 'deshal-bull',
      category: 'Bull',
      image: '/images/p1.jpg',
      isFeatured: true,
      featuredImage: '/images/banner1.jpg',
      price: 170000,
      purchasePrice: 120000,
      cost: 10000,
      tag: 123,
      brand: 'Dutch Dairy',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Deshal Bull',
      breed: 'Bull',
      weight: '500 KG',
      customerName: 'Mr. Sagor',
      customerPhone: '01683785758',
      customerAddress: 'Sec-10, R-12, H-13, Uttara, Dhaka-1230',
      sellerName: 'Rahman Khan',
      sellerAddress: 'Sec-14, R-10, H-13, Mirpur, Dhaka-1230',
      purchaseDate: '2021-02-04',
      sellDate: '2021-02-04',
    },
    {
      name: 'Indial Ox',
      slug: 'indian-ox',
      category: 'Ox',
      image: '/images/p2.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 260000,
      purchasePrice: 220000,
      cost: 12000,
      tag: 124,
      brand: 'dutch',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular indian ox',
      breed: 'Ox',
      weight: '500 KG',
      customerName: 'Mr. Sagor',
      customerPhone: '01683785758',
      customerAddress: 'Sec-10, R-12, H-13, Uttara, Dhaka-1230',
      sellerName: 'Rahman Khan',
      sellerAddress: 'Sec-14, R-10, H-13, Mirpur, Dhaka-1230',
      purchaseDate: '2021-02-04',
      sellDate: '2021-02-04',
    },
    {
      name: 'Pakistani Ox',
      slug: 'indian-ox',
      category: 'Ox',
      image: '/images/p3.jpg',
      isFeatured: false,
      featuredImage: '/images/banner3.jpg',
      price: 260000,
      purchasePrice: 220000,
      cost: 12000,
      tag: 125,
      brand: 'dutch',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular indian ox',
      breed: 'Ox',
      weight: '500 KG',
      customerName: 'Mr. Sagor',
      customerPhone: '01683785758',
      customerAddress: 'Sec-10, R-12, H-13, Uttara, Dhaka-1230',
      sellerName: 'Rahman Khan',
      sellerAddress: 'Sec-14, R-10, H-13, Mirpur, Dhaka-1230',
      purchaseDate: '2021-02-04',
      sellDate: '2021-02-04',
    },
    {
      name: 'Indial Ox',
      slug: 'indian-ox',
      category: 'Ox',
      image: '/images/p4.jpg',
      isFeatured: false,
      featuredImage: '/images/banner4.jpg',
      price: 260000,
      purchasePrice: 220000,
      cost: 12000,
      tag: 126,
      brand: 'dutch',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular indian ox',
      breed: 'Ox',
      weight: '500 KG',
      customerName: 'Mr. Sagor',
      customerPhone: '01683785758',
      customerAddress: 'Sec-10, R-12, H-13, Uttara, Dhaka-1230',
      sellerName: 'Rahman Khan',
      sellerAddress: 'Sec-14, R-10, H-13, Mirpur, Dhaka-1230',
      purchaseDate: '2021-02-04',
      sellDate: '2021-02-04',
    },
    {
      name: 'Indial Ox',
      slug: 'indian-ox',
      category: 'Ox',
      image: '/images/p5.jpg',
      isFeatured: false,
      featuredImage: '/images/banner5.jpg',
      price: 260000,
      purchasePrice: 220000,
      cost: 12000,
      tag: 127,
      brand: 'dutch',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular indian ox',
      breed: 'Ox',
      weight: '500 KG',
      customerName: 'Mr. Sagor',
      customerPhone: '01683785758',
      customerAddress: 'Sec-10, R-12, H-13, Uttara, Dhaka-1230',
      sellerName: 'Rahman Khan',
      sellerAddress: 'Sec-14, R-10, H-13, Mirpur, Dhaka-1230',
      purchaseDate: '2021-02-04',
      sellDate: '2021-02-04',
    },
  ],
};
export default data;
